#!/usr/bin/env python
import string
import random

words = [line.strip() for line in open('./wordlist')]

for x in range (0,10):
    pwd = []
    pwd.append(random.choice(string.digits))
    pwd.append(random.choice(string.digits))
    pwd.append(random.choice(words))
    pwd.append(random.choice(string.punctuation))
    print "".join(pwd)
